namespace Reducers
    class NavigationReducer extends Rotor.Reducer
        override function reducer(state, intent) as object

            if intent.type = IntentTypes.Navigation.GOTO_PAGE
                return {
                    activePageId: intent.payload.pageId,
                    transitionState: "transitioning"
                }

            end if

            return state
        end function
    end class
end namespace
