namespace Interfaces
    interface ContentReaderState
        locale as string
        rowListContent as roSGNode
        statusCode as integer
        ok as boolean
    end interface

end namespace

namespace Models

    class ContentReaderModel extends Rotor.Model

        state = {
            locale: "en_US",
            rowListContent: invalid,
            statusCode: 0,
            ok: false
        } as Interfaces.ContentReaderState

    end class

end namespace
