namespace Interfaces
    interface ContentReaderState
        listContentNode as roSGNodeNode[]
        statusCode as integer
        ok as boolean
    end interface

end namespace

namespace Models

    class ContentReaderModel extends Rotor.Model

        state = {
            listContentNode: [],
            statusCode: 0,
            ok: false
        } as Interfaces.ContentReaderState

    end class

end namespace
