namespace IntentTypes

    enum Navigation
        GOTO_PAGE = "goto_page"
        EXIT_APP = "exit_app"
    end enum

    enum ContentReader
        SET_LOCALE = "set_locale"
        LOAD_CONTENT = "load_content"
        FETCH_DONE = "fetch_done"
        FETCH_ERROR = "fetch_error"
        CONTENT_LOADED = "content_loaded"
        CONTENT_LOAD_ERROR = "content_load_error"
    end enum

end namespace
