namespace tests

@suite
class ExampleTestSuite extends rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("Example tests")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("should pass a simple test")
    function _()
        m.AssertEqual(1 + 1, 2)
    end function

    @it("should pass string comparison")
    function _()
        m.AssertEqual("hello", "hello")
    end function

end class

end namespace
